// Package catalog carries the translation catalogs compiled into a binary, for
// the two programs that must translate themselves with nothing to read on disk:
// the ISO's installer TUI and the standalone shell installer, which runs on a
// stranger's distro. A program that always runs on an installed Ryoku reads
// /usr/share/ryoku/i18n instead and never imports this, so the catalogs stay
// out of its vendor tree.
//
//	i18n.SetFS(catalog.FS)
//	i18n.Use("")
//
// This file exists only to expose the .json files next to it; the catalogs
// themselves are generated by ryoku/i18n/sync.py and are the single source both
// this package and the QML singleton read.
package catalog

import "embed"

//go:embed *.json
var files embed.FS

// FS is the catalog set, keyed by "<code>.json".
var FS = files
