package main

import (
	"fmt"
	"strconv"
	"strings"
)

// settings.kdl generator and the KDL formatting helpers the block writers share.
// The store types, the codec and the block writers live beside this in
// config_store.go, config_layout.go, config_input.go, config_misc.go and
// config_rules.go; this file only orders the blocks and formats their scalars.

// kdlStr quotes a value as a KDL string with the escapes niri's parser accepts.
func kdlStr(s string) string {
	r := strings.NewReplacer("\\", "\\\\", "\"", "\\\"", "\n", "\\n", "\r", "\\r", "\t", "\\t")
	return "\"" + r.Replace(s) + "\""
}

// kdlNum formats a float without a trailing zero exponent, so accel-speed reads
// 0.3 not 3e-01.
func kdlNum(f float64) string {
	return fmt.Sprintf("%g", f)
}

// kdlFloat formats a float that niri's parser insists be a float literal, not an
// integer: a spring damping-ratio of 1 must read "1.0", or niri rejects it as an
// integer where a float scalar is required. A value that already carries a point
// or exponent is left as %g gives it.
func kdlFloat(f float64) string {
	s := strconv.FormatFloat(f, 'g', -1, 64)
	if !strings.ContainsAny(s, ".eE") {
		s += ".0"
	}
	return s
}

// kdlColor normalises a stored hex to niri's "#rrggbb" string; empty stays empty
// so the caller omits the line.
func kdlColor(hex string) string {
	h := strings.TrimSpace(hex)
	if h == "" {
		return ""
	}
	if !strings.HasPrefix(h, "#") {
		h = "#" + h
	}
	return kdlStr(h)
}

const kdlHeader = "// Generated by Ryoku Settings (Super + ,). Edit in the GUI, not here.\n\n"

// genSettings renders settings.kdl from the full effective store. The input,
// layout, cursor and niri-exclusive blocks always carry the baseline; env,
// autostart and window rules are additive, so they appear only when the store
// holds them.
func genSettings(s niriStore) []byte {
	var b strings.Builder
	b.WriteString(kdlHeader)
	writeInput(&b, s.Input, s.Niri)
	writeClipboard(&b, s.Input)
	writeLayout(&b, s.Appearance, s.Niri)
	writeAnimations(&b, s.Appearance, s.Niri)
	writeCursor(&b, s.Cursor)
	writeMisc(&b, s.Niri)
	writeEnvironment(&b, s.Env, s.Apps)
	writeAutostart(&b, s.Autostart)
	writeWindowRules(&b, s.Appearance, s.WindowRules, s.AppOverrides)
	writeBlockOut(&b, s.Niri.BlockOutApps)
	writeLayerRules(&b, s.Niri.LayerRules)
	return []byte(b.String())
}
