#!/usr/bin/env bash
# fixture test for ryoku-windows-entry: the idempotent, marker-fenced edits of
# limine.conf + the chainload entry it emits. disk scan is short-circuited via
# RYOKU_WINDOWS_GUID, so this is hermetic (no real partitions).
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
tool="$here/../system/boot/limine/ryoku-windows-entry"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
state="$tmp/limine-existing-esp"
export RYOKU_EXISTING_ESP_STATE="$state"

fail() { echo "FAIL: $1" >&2; exit 1; }

conf="$tmp/limine.conf"
cat >"$conf" <<'EOF'
timeout: 3
default_entry: 1

/Ryoku Linux
    protocol: efi
    path: boot():/EFI/Linux/ryoku.efi
EOF

# --- emit -----------------------------------------------------------------
out="$("$tool" emit AAAA-BBBB)"
grep -qF 'path: uuid(AAAA-BBBB):/EFI/Microsoft/Boot/bootmgfw.efi' <<<"$out" \
  || fail "emit did not produce a uuid()-addressed Windows path"
grep -qxF '/Windows' <<<"$out" || fail "emit missing the /Windows title"
grep -qF 'protocol: efi_chainload' <<<"$out" || fail "emit missing the chainload protocol"

# --- sync: add managed block, keep existing entries -----------------------
RYOKU_WINDOWS_GUID="1111-2222" "$tool" sync "$conf" >/dev/null
grep -qF '/Ryoku Linux' "$conf" || fail "sync clobbered the existing kernel entry"
grep -qF 'path: uuid(1111-2222):/EFI/Microsoft/Boot/bootmgfw.efi' "$conf" \
  || fail "sync did not write the Windows entry"
[[ "$(grep -c '^/Windows$' "$conf")" == 1 ]] || fail "expected exactly one /Windows entry"
grep -qE '^# >>> ryoku-windows-entry' "$conf" || fail "missing managed begin fence"

# --- second sync with same GUID = no dup ----------------------------------
RYOKU_WINDOWS_GUID="1111-2222" "$tool" sync "$conf" >/dev/null
[[ "$(grep -c '^/Windows$' "$conf")" == 1 ]] || fail "sync duplicated the Windows entry"

# --- new GUID swaps in place ----------------------------------------------
RYOKU_WINDOWS_GUID="3333-4444" "$tool" sync "$conf" >/dev/null
grep -qF 'uuid(3333-4444)' "$conf" || fail "sync did not update to the new GUID"
grep -qF 'uuid(1111-2222)' "$conf" && fail "sync left the stale GUID behind"
[[ "$(grep -c '^/Windows$' "$conf")" == 1 ]] || fail "update left more than one Windows entry"

# --- no Windows detected: existing managed block stays ---------------------
cp "$conf" "$tmp/before.conf"
RYOKU_WINDOWS_GUID="" "$tool" sync "$conf" >/dev/null
diff -q "$tmp/before.conf" "$conf" >/dev/null || fail "sync changed conf when no Windows detected"

# --- no Windows on a clean conf: nothing added ----------------------------
cat >"$tmp/clean.conf" <<'EOF'
timeout: 3
/Ryoku Linux
    protocol: efi
    path: boot():/EFI/Linux/ryoku.efi
EOF
RYOKU_WINDOWS_GUID="" "$tool" sync "$tmp/clean.conf" >/dev/null
grep -qF '/Windows' "$tmp/clean.conf" && fail "sync added a Windows entry when none detected"

# --- adoption interleave regression (limine-entry-tool 1.37) --------------
# 1.37 adopts the flat "/Ryoku Linux" placeholder into a directory and re-emits
# our begin fence ABOVE the generated "//<kernel>" UKI children, with /Windows
# and the end fence trailing. A fence-to-fence strip would swallow the kernels
# and flatten the menu; the title-anchored strip must keep them, dedup /Windows
# to one block, and swap in the fresh GUID.
adopt="$tmp/adopted.conf"
cat >"$adopt" <<'EOF'
timeout: 3
default_entry: 1

/Ryoku Linux
    protocol: efi
    path: boot():/EFI/Linux/ryoku_linux.efi
# >>> ryoku-windows-entry (managed) >>>
  //linux
  ### auto-generated by limine-entry-tool
  comment: Kernel version: 7.0.12
  protocol: efi
  path: boot():/EFI/Linux/ryoku_linux.efi
/Windows
    comment: Boot into Windows
    protocol: efi_chainload
    path: uuid(stale-guid):/EFI/Microsoft/Boot/bootmgfw.efi
# <<< ryoku-windows-entry (managed) <<<
EOF

RYOKU_WINDOWS_GUID="5555-6666" "$tool" sync "$adopt" >/dev/null
grep -qF '  //linux' "$adopt" || fail "adoption strip swallowed the //linux UKI entry"
grep -qF 'path: boot():/EFI/Linux/ryoku_linux.efi' "$adopt" \
  || fail "adoption strip dropped the UKI entry body"
grep -qF 'comment: Kernel version: 7.0.12' "$adopt" \
  || fail "adoption strip dropped the UKI comment"
grep -qF 'uuid(5555-6666)' "$adopt" || fail "adoption sync did not write the fresh Windows GUID"
grep -qF 'uuid(stale-guid)' "$adopt" && fail "adoption sync left the stale Windows GUID"
[[ "$(grep -c '^/Windows$' "$adopt")" == 1 ]] || fail "adoption sync did not dedup to one /Windows"
[[ "$(grep -cE '^# >>> ryoku-windows-entry' "$adopt")" == 1 ]] \
  || fail "adoption sync left more than one managed begin fence"

# idempotent: a second sync is byte-identical.
cp "$adopt" "$tmp/adopted-before.conf"
RYOKU_WINDOWS_GUID="5555-6666" "$tool" sync "$adopt" >/dev/null
diff -q "$tmp/adopted-before.conf" "$adopt" >/dev/null \
  || fail "second adoption sync changed the file"

# --- fence tolerance: an indented begin/end fence is still stripped --------
# 1.37 may serialize the attached fence configLine indented under the adopted
# directory; the trim in strip_managed must still remove it exactly, so the
# managed block never accumulates stray fence comments.
indent="$tmp/indented.conf"
cat >"$indent" <<'EOF'
timeout: 3

/Ryoku Linux
    protocol: efi
    path: boot():/EFI/Linux/ryoku_linux.efi
    # >>> ryoku-windows-entry (managed) >>>
  //linux
  protocol: efi
  path: boot():/EFI/Linux/ryoku_linux.efi
/Windows
    comment: Boot into Windows
    protocol: efi_chainload
    path: uuid(old):/EFI/Microsoft/Boot/bootmgfw.efi
    # <<< ryoku-windows-entry (managed) <<<
EOF

RYOKU_WINDOWS_GUID="7777-8888" "$tool" sync "$indent" >/dev/null
grep -qF '  //linux' "$indent" || fail "indented-fence strip swallowed the //linux UKI entry"
[[ "$(grep -cF 'ryoku-windows-entry (managed)' "$indent")" == 2 ]] \
  || fail "indented-fence strip did not collapse to one managed block"
grep -qF 'uuid(7777-8888)' "$indent" || fail "indented-fence sync did not write the fresh GUID"
grep -qF 'uuid(old)' "$indent" && fail "indented-fence sync left the stale GUID"

# --- shared ESP (Windows' ESP IS Limine's boot volume): boot(), not uuid() -----
# the alongside pivot: a uuid() chainload to Limine's own boot volume panics on
# 9.x+, so when the conf's volume PARTUUID matches the detected Windows GUID the
# entry must be protocol efi + boot():/...
shared="$tmp/shared.conf"
printf '/Ryoku Linux\n    protocol: linux\n' >"$shared"
RYOKU_WINDOWS_GUID="5eaf9964-1111-2222-3333-444455556666" \
RYOKU_CONF_PARTUUID="5EAF9964-1111-2222-3333-444455556666" \
  "$tool" sync "$shared" >/dev/null
grep -qF 'protocol: efi' "$shared" || fail "shared-ESP entry is not protocol efi"
grep -qF 'path: boot():/EFI/Microsoft/Boot/bootmgfw.efi' "$shared" \
  || fail "shared-ESP entry did not use boot():"
grep -qF 'uuid(' "$shared" && fail "shared-ESP entry used uuid() (would panic on the boot volume)"
grep -qF 'protocol: efi_chainload' "$shared" && fail "shared-ESP entry used efi_chainload"

# --- cross-drive Windows (different volume): still uuid() ----------------------
cross="$tmp/cross.conf"
printf '/Ryoku Linux\n    protocol: linux\n' >"$cross"
RYOKU_WINDOWS_GUID="5eaf9964-1111-2222-3333-444455556666" \
RYOKU_CONF_PARTUUID="aaaaaaaa-0000-0000-0000-000000000000" \
  "$tool" sync "$cross" >/dev/null
grep -qF 'path: uuid(5eaf9964-1111-2222-3333-444455556666):/EFI/Microsoft/Boot/bootmgfw.efi' "$cross" \
  || fail "cross-drive Windows must stay uuid()"

# --- recorded non-Windows ESP survives future menu rewrites ----------------
neighbor="$tmp/neighbor.conf"
printf '/Ryoku Linux\n    protocol: linux\n' >"$neighbor"
printf 'linux\t9999-aaaa\t/EFI/systemd/systemd-bootx64.efi\n' >"$state"
RYOKU_WINDOWS_GUID="" "$tool" sync "$neighbor" >/dev/null
grep -qF '/Linux (existing)' "$neighbor" || fail "recorded Linux entry was not added"
grep -qF 'path: uuid(9999-aaaa):/EFI/systemd/systemd-bootx64.efi' "$neighbor" \
  || fail "recorded Linux entry did not use its preserved ESP metadata"

cp "$neighbor" "$tmp/neighbor-before.conf"
RYOKU_WINDOWS_GUID="" "$tool" sync "$neighbor" >/dev/null
diff -q "$tmp/neighbor-before.conf" "$neighbor" >/dev/null \
  || fail "recorded Linux entry sync is not idempotent"

printf 'ryoku\tbbbb-cccc\t/EFI/limine/limine_x64.efi\n' >"$state"
RYOKU_WINDOWS_GUID="" "$tool" sync "$neighbor" >/dev/null
grep -qF '/Ryoku (existing)' "$neighbor" || fail "recorded Ryoku entry was not updated"
grep -qF 'uuid(bbbb-cccc):/EFI/limine/limine_x64.efi' "$neighbor" \
  || fail "recorded Ryoku entry did not use the updated metadata"
grep -qF '/Linux (existing)' "$neighbor" && fail "recorded entry update left the old Linux title"

printf '/Ryoku Linux\n    protocol: efi\n' >"$neighbor"
RYOKU_WINDOWS_GUID="" "$tool" sync "$neighbor" >/dev/null
grep -qF '/Ryoku (existing)' "$neighbor" \
  || fail "post-update sync did not restore the recorded neighboring OS"

# --- alongside TWO-STAGE limine generator (stage-1 hop + stage-2 /boot conf) -----
# stage 1 lives on the shared ESP beside our BOOTX64.EFI: a STATIC hop that only
# chainloads the second-stage limine on the RYOKUBOOT volume (timeout 0). stage 2
# lives on the XBOOTLDR /boot, so boot() there is the XBOOTLDR: the existing OS on
# the shared ESP is addressed by guid(<shared-ESP PARTUUID>), never boot():/EFI/... .
repo="$here/.."
# shellcheck source=/dev/null
source "$repo/installation/backend/lib/common.sh"
# shellcheck source=/dev/null
source "$repo/installation/backend/lib/disk.sh"
# shellcheck source=/dev/null
source "$repo/installation/backend/lib/bootloader.sh"
export RYOKU_REPO="$repo" CMDLINE="root=UUID=deadbeef rw"

# STAGE 1 hop: timeout 0 + exactly one fslabel(RYOKUBOOT) efi_chainload entry, and
# NOTHING else -- no branding globals, no kernel entry, no existing-OS entry.
hop="$(ryoku_stage1_hop_text)"
grep -qxF 'timeout: 0' <<<"$hop" || fail "stage-1 hop is not timeout 0"
grep -qF 'protocol: efi_chainload' <<<"$hop" || fail "stage-1 hop is not an efi_chainload"
grep -qF 'image_path: fslabel(RYOKUBOOT):/ryoku-limine.efi' <<<"$hop" || fail "stage-1 hop does not chainload the second-stage limine by fslabel(RYOKUBOOT)"
[[ "$(grep -c '^/' <<<"$hop")" == 1 ]] || fail "stage-1 hop has more than the single chainload entry"
grep -qF 'fslabel(RYOKUBOOT):/vmlinuz-linux' <<<"$hop" && fail "stage-1 hop must not carry a kernel entry (that is the stage-2 menu)"
grep -qiF 'interface_branding' <<<"$hop" && fail "stage-1 hop must stay a bare hop (no branding globals)"

# STAGE 2 /boot conf: branding + fslabel(RYOKUBOOT) kernels + guid() existing-OS
# chainload. windows kind:
win_conf="$(ryoku_alongside_conf_text windows /EFI/Microsoft/Boot/bootmgfw.efi 1111-2222)"
grep -qF 'interface_branding: Ryoku Bootloader' <<<"$win_conf" || fail "stage-2 conf lost the branding globals"
grep -qF 'kernel_path: fslabel(RYOKUBOOT):/vmlinuz-linux' <<<"$win_conf" || fail "stage-2 conf missing the fslabel(RYOKUBOOT) kernel path"
grep -qF 'module_path: fslabel(RYOKUBOOT):/initramfs-linux.img' <<<"$win_conf" || fail "stage-2 conf missing the fslabel(RYOKUBOOT) initramfs path"
grep -qxF '/Windows' <<<"$win_conf" || fail "stage-2 windows conf missing the /Windows entry"
grep -qF 'image_path: guid(1111-2222):/EFI/Microsoft/Boot/bootmgfw.efi' <<<"$win_conf" || fail "stage-2 windows conf did not chainload bootmgfw by guid()"
grep -qF 'protocol: efi_chainload' <<<"$win_conf" || fail "stage-2 windows conf is not an efi_chainload"
grep -qF 'comment: Windows Boot Manager' <<<"$win_conf" || fail "stage-2 windows conf lost the Windows comment"

# ryoku/linux kinds: guid()-addressed "(existing)" chainload, labeled by kind.
ryoku_conf="$(ryoku_alongside_conf_text ryoku /EFI/limine/limine_x64.efi 3333-4444)"
grep -qxF '/Ryoku (existing)' <<<"$ryoku_conf" || fail "stage-2 ryoku conf missing the '/Ryoku (existing)' entry"
grep -qF 'image_path: guid(3333-4444):/EFI/limine/limine_x64.efi' <<<"$ryoku_conf" || fail "stage-2 ryoku conf did not chainload the existing limine by guid()"
grep -qF 'comment: existing ryoku install' <<<"$ryoku_conf" || fail "stage-2 ryoku conf lost the existing-install comment"
grep -qF '/Windows' <<<"$ryoku_conf" && fail "stage-2 ryoku conf wrongly emitted a /Windows entry"

linux_conf="$(ryoku_alongside_conf_text linux /EFI/systemd/systemd-bootx64.efi 5555-6666)"
grep -qxF '/Linux (existing)' <<<"$linux_conf" || fail "stage-2 linux conf missing the '/Linux (existing)' entry"
grep -qF 'image_path: guid(5555-6666):/EFI/systemd/systemd-bootx64.efi' <<<"$linux_conf" || fail "stage-2 linux conf did not chainload the vendor binary by guid()"

# existing_boot none: no chainload entry, kernel entry still present.
none_conf="$(ryoku_alongside_conf_text ryoku none 7777-8888)"
grep -qF '(existing)' <<<"$none_conf" && fail "stage-2 conf with existing_boot none wrongly emitted a chainload entry"
grep -qF 'kernel_path: fslabel(RYOKUBOOT):/vmlinuz-linux' <<<"$none_conf" || fail "stage-2 none conf lost the Ryoku Linux entry"

# the cardinal stage-2 rule: NO boot():/EFI cross-volume path (boot() is the
# XBOOTLDR here, so a boot():/EFI/... would reach the wrong volume and never open
# the existing OS). assert it across every kind.
for c in "$win_conf" "$ryoku_conf" "$linux_conf" "$none_conf"; do
  grep -qF 'boot():/EFI' <<<"$c" && fail "stage-2 conf used a boot():/EFI cross-volume path (must be guid())"
done
echo "limine-windows: two-stage generator (hop + windows/ryoku/linux/none, no boot():/EFI) checks passed"

echo "limine-windows: all checks passed"
