package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// Recipes pin proposed commands under rr- names. Every save rebuilds the
// Fish, Bash, and Zsh prompt-expansion files from the same sorted list. The
// regenerable store and generated files live under XDG_STATE_HOME.

type Recipe struct {
	Name string `json:"name"`
	Run  string `json:"run"`
	Why  string `json:"why,omitempty"`
	At   string `json:"at"`
}

func recipesPath() string {
	return filepath.Join(xdgState(), "ryoku", "rashin-recipes.json")
}

// RecipesFishPath is the generated abbreviation file conf.d sources.
func RecipesFishPath() string {
	return filepath.Join(xdgState(), "ryoku", "rashin-recipes.fish")
}

func RecipesBashPath() string {
	return filepath.Join(xdgState(), "ryoku", "rashin-recipes.bash")
}

func RecipesZshPath() string {
	return filepath.Join(xdgState(), "ryoku", "rashin-recipes.zsh")
}

var recipeName = regexp.MustCompile(`^[a-z0-9][a-z0-9-]{0,23}$`)

func LoadRecipes() []Recipe {
	b, err := os.ReadFile(recipesPath())
	if err != nil {
		return nil
	}
	var rs []Recipe
	if json.Unmarshal(b, &rs) != nil {
		return nil
	}
	return rs
}

func saveRecipes(rs []Recipe) error {
	sort.Slice(rs, func(i, j int) bool { return rs[i].Name < rs[j].Name })
	b, err := json.MarshalIndent(rs, "", "  ")
	if err != nil {
		return err
	}
	p := recipesPath()
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		return err
	}
	if err := atomicWrite(p, append(b, '\n'), 0o644); err != nil {
		return err
	}
	return materializeRecipeFiles(rs)
}

// SaveRecipe upserts one recipe and rebuilds the abbreviation file.
func SaveRecipe(name, run, why string) error {
	name = strings.TrimSpace(name)
	if !recipeName.MatchString(name) {
		return fmt.Errorf("recipe names are short lowercase [a-z0-9-], got %q", name)
	}
	if strings.TrimSpace(run) == "" {
		return fmt.Errorf("nothing to save: no command")
	}
	rs := LoadRecipes()
	for i := range rs {
		if rs[i].Name == name {
			rs[i].Run, rs[i].Why, rs[i].At = run, why, nowRFC3339()
			return saveRecipes(rs)
		}
	}
	rs = append(rs, Recipe{Name: name, Run: run, Why: why, At: nowRFC3339()})
	return saveRecipes(rs)
}

// RemoveRecipe deletes by name; unknown names error so a typo is visible.
func RemoveRecipe(name string) error {
	rs := LoadRecipes()
	for i := range rs {
		if rs[i].Name == name {
			return saveRecipes(append(rs[:i], rs[i+1:]...))
		}
	}
	return fmt.Errorf("no recipe named %q", name)
}

func materializeRecipeFiles(rs []Recipe) error {
	var fish, bash, zsh strings.Builder
	fish.WriteString("# Generated by ryoku-rashin; do not edit.\n")
	bash.WriteString("# Generated by ryoku-rashin; do not edit.\n")
	zsh.WriteString("# Generated by ryoku-rashin; do not edit.\n")
	for _, r := range rs {
		fmt.Fprintf(&fish, "abbr -a -- rr-%s %s\n", r.Name, fishQuote(r.Run))
		fmt.Fprintf(&bash, "ble-sabbrev rr-%s=%s\n", r.Name, shQuote(r.Run))
		fmt.Fprintf(&zsh, "alias rr-%s=%s\n", r.Name, shQuote(r.Run))
	}
	for path, body := range map[string]string{
		RecipesFishPath(): fish.String(),
		RecipesBashPath(): bash.String(),
		RecipesZshPath():  zsh.String(),
	} {
		if err := atomicWrite(path, []byte(body), 0o644); err != nil {
			return err
		}
	}
	return nil
}

// fishQuote single-quotes a string for fish: inside single quotes fish only
// treats \' and \\ specially, so escaping those two is complete.
func fishQuote(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `'`, `\'`)
	return "'" + s + "'"
}

// lastPlanPath persists the newest terminal plan so `rashin --last` and
// `rashin recipe save` survive daemon and terminal restarts.
func lastPlanPath() string {
	return filepath.Join(xdgState(), "ryoku", "rashin-last.json")
}

type lastTerm struct {
	At     string    `json:"at"`
	Q      string    `json:"q"`
	Answer string    `json:"answer"`
	Plan   *termPlan `json:"plan,omitempty"`
}

func recordLastTerm(l lastTerm) {
	b, err := json.Marshal(l)
	if err != nil {
		return
	}
	if os.MkdirAll(filepath.Dir(lastPlanPath()), 0o755) != nil {
		return
	}
	_ = atomicWrite(lastPlanPath(), append(b, '\n'), 0o644)
}

func loadLastTerm() (lastTerm, error) {
	var l lastTerm
	b, err := os.ReadFile(lastPlanPath())
	if err != nil {
		return l, err
	}
	err = json.Unmarshal(b, &l)
	return l, err
}

// runRecord is one executed rashin-proposed command, reported by a shell
// post-command hook (or --run). The habits layer mines these for corrections.
type runRecord struct {
	At       string `json:"at"`
	Proposed string `json:"proposed"`
	Ran      string `json:"ran"`
	Status   int    `json:"status"`
}

const runHistoryCap = 60

func runsPath() string {
	return filepath.Join(xdgState(), "ryoku", "rashin-runs.jsonl")
}

func recordRun(rec runRecord) {
	if strings.TrimSpace(rec.Ran) == "" {
		return
	}
	askHistoryMu.Lock()
	defer askHistoryMu.Unlock()
	recs := readRunsLocked()
	recs = append(recs, rec)
	if len(recs) > runHistoryCap {
		recs = recs[len(recs)-runHistoryCap:]
	}
	if os.MkdirAll(filepath.Dir(runsPath()), 0o755) != nil {
		return
	}
	var b strings.Builder
	enc := json.NewEncoder(&b)
	for _, r := range recs {
		_ = enc.Encode(r)
	}
	_ = atomicWrite(runsPath(), []byte(b.String()), 0o644)
}

func readRunsLocked() []runRecord {
	b, err := os.ReadFile(runsPath())
	if err != nil {
		return nil
	}
	var out []runRecord
	for _, line := range strings.Split(string(b), "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		var r runRecord
		if json.Unmarshal([]byte(line), &r) == nil && r.Ran != "" {
			out = append(out, r)
		}
	}
	return out
}

// RecentRuns returns up to n run reports, newest first.
func RecentRuns(n int) []runRecord {
	askHistoryMu.Lock()
	recs := readRunsLocked()
	askHistoryMu.Unlock()
	for i, j := 0, len(recs)-1; i < j; i, j = i+1, j-1 {
		recs[i], recs[j] = recs[j], recs[i]
	}
	if n > 0 && len(recs) > n {
		recs = recs[:n]
	}
	return recs
}
