blank_issues_enabled: false
contact_links:
  - name: Suggestion
    url: https://github.com/ryoku-dev/ryoku/discussions
    about: Suggest a new feature, change to existing feature, or other ideas in Discussions.
