package updater

import "testing"

// the shape limine-snapper-sync generates (comments and paths trimmed).
const limineFixture = `timeout: 3
default_entry: Ryoku Linux/linux
/Ryoku Linux
    //linux
        comment: kernel-id=linux
        cmdline: quiet root=UUID=x rootflags=subvol=@ rw
//Snapshots
    ### Auto-generated by limine-snapper-sync
    ///2026-09-03 14:07:46
        comment: inotify-tools
        ////linux
            comment: kernel-id=linux
            protocol: efi
            cmdline: quiet root=UUID=x rootflags=subvol=/@snapshots/570/snapshot rw
        ////linux-cachyos
            cmdline: quiet root=UUID=x rootflags=subvol=/@snapshots/570/snapshot rw
    ///2026-09-02 21:00:00
        ////linux
            cmdline: quiet root=UUID=x rootflags=subvol=/@snapshots/565/snapshot rw
`

func TestSnapshotEntryPathFindsTheNestedEntry(t *testing.T) {
	if got := snapshotEntryPath(limineFixture, "570"); got != "Snapshots/2026-09-03 14:07:46/linux" {
		t.Fatalf("570 -> %q", got)
	}
	if got := snapshotEntryPath(limineFixture, "565"); got != "Snapshots/2026-09-02 21:00:00/linux" {
		t.Fatalf("565 -> %q", got)
	}
	if got := snapshotEntryPath(limineFixture, "999"); got != "" {
		t.Fatalf("unknown snapshot must not match, got %q", got)
	}
	// a subvol match outside //Snapshots (the live entry) never counts
	if got := snapshotEntryPath("//Live\n    ///x\n        ////linux\n            cmdline: rootflags=subvol=/@snapshots/570/snapshot\n", "570"); got != "" {
		t.Fatalf("entry outside Snapshots matched: %q", got)
	}
}
