package main

import (
	"fmt"
	"strings"
)

// The settings.lua generator: appearance / input / cursor / animation leaves as
// diffs against the shipped defaults, window / layer / app rules, gestures, the
// start hook, and the full-config form the preview eval uses.

const luaHeader = `-- Generated by Ryoku Settings (Super + ,). Lives in the user_edits overlay,
-- overwritten on every change, so change it in the GUI, not by hand. Loaded
-- after Ryoku's defaults and before your user.lua, which still wins.

`

func genLua(o Overrides, follow bool) string {
	var b strings.Builder
	b.WriteString(luaHeader)

	if cfg := genConfig(o, follow); cfg != "" {
		b.WriteString(cfg)
	}
	if m := genMotion(o, false); m != "" {
		b.WriteString(m)
	}
	if ab := genAnimatedBorder(o, follow, false); ab != "" {
		b.WriteString(ab)
	}
	if anim := genAnimBlock(o); anim != "" {
		b.WriteString(anim)
		b.WriteString("\n")
	}
	if g := genGesture(o); g != "" {
		b.WriteString(g)
		b.WriteString("\n")
	}
	// cursor divergence exports env too so spawned apps see the picked cursor
	// (the start hook's setcursor only reaches the compositor + XWayland).
	if d := defaultOverrides().Cursor; o.Cursor.Theme != d.Theme || o.Cursor.Size != d.Size {
		fmt.Fprintf(&b, "hl.env(%s, %s)\n", luaStr("XCURSOR_THEME"), luaStr(o.Cursor.Theme))
		fmt.Fprintf(&b, "hl.env(%s, %s)\n", luaStr("XCURSOR_SIZE"), luaStr(fmt.Sprintf("%d", o.Cursor.Size)))
		fmt.Fprintf(&b, "hl.env(%s, %s)\n", luaStr("HYPRCURSOR_THEME"), luaStr(o.Cursor.Theme))
		fmt.Fprintf(&b, "hl.env(%s, %s)\n\n", luaStr("HYPRCURSOR_SIZE"), luaStr(fmt.Sprintf("%d", o.Cursor.Size)))
	}
	for _, e := range o.Env {
		if strings.TrimSpace(e.Key) == "" {
			continue
		}
		fmt.Fprintf(&b, "hl.env(%s, %s)\n", luaStr(e.Key), luaStr(e.Value))
	}
	if len(o.Env) > 0 {
		b.WriteString("\n")
	}
	if ap := genApps(o); ap != "" {
		b.WriteString(ap)
	}
	if tm := genTameMaximizeOnOpen(o); tm != "" {
		b.WriteString(tm)
	}
	for i, r := range o.WindowRules {
		if rl := genWindowRule(i, r); rl != "" {
			b.WriteString(rl)
		}
	}
	for i, r := range o.LayerRules {
		if rl := genLayerRule(i, r); rl != "" {
			b.WriteString(rl)
		}
	}
	for i, a := range o.AppOverrides {
		if rl := genAppOverride(i, a); rl != "" {
			b.WriteString(rl)
		}
	}
	if ub := genUnbinds(o); ub != "" {
		b.WriteString(ub)
	}
	for _, k := range o.Keybinds {
		if kb := genKeybind(k); kb != "" {
			b.WriteString(kb)
		}
	}
	if pl := genPlugins(o); pl != "" {
		b.WriteString(pl)
	}
	if start := genStartHook(o); start != "" {
		b.WriteString("\n")
		b.WriteString(start)
	}
	return b.String()
}

// genApps exports env vars for the chosen browser and terminal so the CLI and
// xdg-open honour the same choice the keybinds launch; a later hl.env wins over
// env.lua. The editor keeps env.lua's default (a terminal editor wants the bare
// binary), so it is set through the Environment page instead.
func genApps(o Overrides) string {
	var b strings.Builder
	if v := strings.TrimSpace(o.Apps["browser"]); v != "" {
		fmt.Fprintf(&b, "hl.env(%s, %s)\n", luaStr("BROWSER"), luaStr(v))
	}
	if v := strings.TrimSpace(o.Apps["terminal"]); v != "" {
		fmt.Fprintf(&b, "hl.env(%s, %s)\n", luaStr("TERMINAL"), luaStr(v))
	}
	if b.Len() > 0 {
		b.WriteString("\n")
	}
	return b.String()
}

// genConfig: one hl.config({...}) holding only the leaves that diverge from the
// defaults. Once input settings were saved the kb_* keys are pinned
// unconditionally, because keyboard.lua loads before settings.lua and a
// diffed-away "us" would silently win over what the UI shows.
func genConfig(o Overrides, follow bool) string {
	d := defaultOverrides()
	var general, deco, input, cursor, misc, gestures, dwindle, master []string

	a, da := o.Appearance, d.Appearance
	if a.GapsIn != da.GapsIn {
		general = append(general, fmt.Sprintf("gaps_in = %d", a.GapsIn))
	}
	if a.GapsOut != da.GapsOut {
		general = append(general, fmt.Sprintf("gaps_out = %d", a.GapsOut))
	}
	if a.BorderSize != da.BorderSize {
		general = append(general, fmt.Sprintf("border_size = %d", a.BorderSize))
	}
	if a.Layout != da.Layout {
		general = append(general, fmt.Sprintf("layout = %s", luaStr(a.Layout)))
	}
	if a.ResizeOnBorder != da.ResizeOnBorder {
		general = append(general, fmt.Sprintf("resize_on_border = %t", a.ResizeOnBorder))
	}
	if a.SnapEnabled != da.SnapEnabled {
		general = append(general, fmt.Sprintf("snap = { enabled = %t }", a.SnapEnabled))
	}
	if a.AnimatedBorder {
		// the active border is a rotating gradient (genAnimatedBorder); only the
		// inactive colour is a plain override, and only when colours are fixed.
		if !follow {
			general = append(general, fmt.Sprintf("[\"col.inactive_border\"] = %s", luaStr(luaRGB(a.InactiveBorder))))
		}
	} else if !follow {
		general = append(general, fmt.Sprintf("[\"col.active_border\"] = %s", luaStr(luaRGB(a.ActiveBorder))))
		general = append(general, fmt.Sprintf("[\"col.inactive_border\"] = %s", luaStr(luaRGB(a.InactiveBorder))))
	}
	if a.ExtendBorderGrab != da.ExtendBorderGrab {
		general = append(general, fmt.Sprintf("extend_border_grab_area = %d", a.ExtendBorderGrab))
	}
	if a.HoverIconOnBorder != da.HoverIconOnBorder {
		general = append(general, fmt.Sprintf("hover_icon_on_border = %t", a.HoverIconOnBorder))
	}
	if a.NoFocusFallback != da.NoFocusFallback {
		general = append(general, fmt.Sprintf("no_focus_fallback = %t", a.NoFocusFallback))
	}
	if a.ResizeCorner != da.ResizeCorner {
		general = append(general, fmt.Sprintf("resize_corner = %d", a.ResizeCorner))
	}
	if a.GapsWorkspaces != da.GapsWorkspaces {
		general = append(general, fmt.Sprintf("gaps_workspaces = %d", a.GapsWorkspaces))
	}

	if a.Rounding != da.Rounding {
		deco = append(deco, fmt.Sprintf("rounding = %d", a.Rounding))
	}
	if a.RoundingPower != da.RoundingPower {
		deco = append(deco, fmt.Sprintf("rounding_power = %s", luaNum(a.RoundingPower)))
	}
	if a.ActiveOpacity != da.ActiveOpacity {
		deco = append(deco, fmt.Sprintf("active_opacity = %s", luaNum(a.ActiveOpacity)))
	}
	if a.InactiveOpacity != da.InactiveOpacity {
		deco = append(deco, fmt.Sprintf("inactive_opacity = %s", luaNum(a.InactiveOpacity)))
	}
	if a.DimInactive != da.DimInactive {
		deco = append(deco, fmt.Sprintf("dim_inactive = %t", a.DimInactive))
	}
	if a.DimStrength != da.DimStrength {
		deco = append(deco, fmt.Sprintf("dim_strength = %s", luaNum(a.DimStrength)))
	}
	if a.FullscreenOpacity != da.FullscreenOpacity {
		deco = append(deco, fmt.Sprintf("fullscreen_opacity = %s", luaNum(a.FullscreenOpacity)))
	}
	if a.DimSpecial != da.DimSpecial {
		deco = append(deco, fmt.Sprintf("dim_special = %s", luaNum(a.DimSpecial)))
	}
	if a.DimAround != da.DimAround {
		deco = append(deco, fmt.Sprintf("dim_around = %s", luaNum(a.DimAround)))
	}
	if a.DimModal != da.DimModal {
		deco = append(deco, fmt.Sprintf("dim_modal = %t", a.DimModal))
	}
	if a.BorderPartOfWindow != da.BorderPartOfWindow {
		deco = append(deco, fmt.Sprintf("border_part_of_window = %t", a.BorderPartOfWindow))
	}
	var blur []string
	if a.BlurEnabled != da.BlurEnabled {
		blur = append(blur, fmt.Sprintf("enabled = %t", a.BlurEnabled))
	}
	if a.BlurSize != da.BlurSize {
		blur = append(blur, fmt.Sprintf("size = %d", a.BlurSize))
	}
	if a.BlurPasses != da.BlurPasses {
		blur = append(blur, fmt.Sprintf("passes = %d", a.BlurPasses))
	}
	if a.BlurXray != da.BlurXray {
		blur = append(blur, fmt.Sprintf("xray = %t", a.BlurXray))
	}
	if a.BlurVibrancy != da.BlurVibrancy {
		blur = append(blur, fmt.Sprintf("vibrancy = %s", luaNum(a.BlurVibrancy)))
	}
	if a.BlurNoise != da.BlurNoise {
		blur = append(blur, fmt.Sprintf("noise = %s", luaNum(a.BlurNoise)))
	}
	if a.BlurContrast != da.BlurContrast {
		blur = append(blur, fmt.Sprintf("contrast = %s", luaNum(a.BlurContrast)))
	}
	if a.BlurBrightness != da.BlurBrightness {
		blur = append(blur, fmt.Sprintf("brightness = %s", luaNum(a.BlurBrightness)))
	}
	if a.BlurSpecial != da.BlurSpecial {
		blur = append(blur, fmt.Sprintf("special = %t", a.BlurSpecial))
	}
	if a.BlurPopups != da.BlurPopups {
		blur = append(blur, fmt.Sprintf("popups = %t", a.BlurPopups))
	}
	if a.BlurIgnoreOpacity != da.BlurIgnoreOpacity {
		blur = append(blur, fmt.Sprintf("ignore_opacity = %t", a.BlurIgnoreOpacity))
	}
	if a.BlurNewOptimizations != da.BlurNewOptimizations {
		blur = append(blur, fmt.Sprintf("new_optimizations = %t", a.BlurNewOptimizations))
	}
	if a.BlurVibrancyDarkness != da.BlurVibrancyDarkness {
		blur = append(blur, fmt.Sprintf("vibrancy_darkness = %s", luaNum(a.BlurVibrancyDarkness)))
	}
	if len(blur) > 0 {
		deco = append(deco, "blur = { "+strings.Join(blur, ", ")+" }")
	}
	var shadow []string
	if a.ShadowEnabled != da.ShadowEnabled {
		shadow = append(shadow, fmt.Sprintf("enabled = %t", a.ShadowEnabled))
	}
	if a.ShadowRange != da.ShadowRange {
		shadow = append(shadow, fmt.Sprintf("range = %d", a.ShadowRange))
	}
	if a.ShadowPower != da.ShadowPower {
		shadow = append(shadow, fmt.Sprintf("render_power = %d", a.ShadowPower))
	}
	if a.ShadowSharp != da.ShadowSharp {
		shadow = append(shadow, fmt.Sprintf("sharp = %t", a.ShadowSharp))
	}
	if a.ShadowScale != da.ShadowScale {
		shadow = append(shadow, fmt.Sprintf("scale = %s", luaNum(a.ShadowScale)))
	}
	if a.ShadowColor != da.ShadowColor {
		shadow = append(shadow, fmt.Sprintf("color = %s", luaStr(luaRGB(a.ShadowColor))))
	}
	if len(shadow) > 0 {
		deco = append(deco, "shadow = { "+strings.Join(shadow, ", ")+" }")
	}
	var glow []string
	if a.GlowEnabled != da.GlowEnabled {
		glow = append(glow, fmt.Sprintf("enabled = %t", a.GlowEnabled))
	}
	if a.GlowRange != da.GlowRange {
		glow = append(glow, fmt.Sprintf("range = %d", a.GlowRange))
	}
	if a.GlowColor != da.GlowColor {
		glow = append(glow, fmt.Sprintf("color = %s", luaStr(luaRGB(a.GlowColor))))
	}
	if len(glow) > 0 {
		deco = append(deco, "glow = { "+strings.Join(glow, ", ")+" }")
	}

	dw, ddw := o.Dwindle, d.Dwindle
	if dw.PreserveSplit != ddw.PreserveSplit {
		dwindle = append(dwindle, fmt.Sprintf("preserve_split = %t", dw.PreserveSplit))
	}
	if dw.SmartSplit != ddw.SmartSplit {
		dwindle = append(dwindle, fmt.Sprintf("smart_split = %t", dw.SmartSplit))
	}
	if dw.SmartResizing != ddw.SmartResizing {
		dwindle = append(dwindle, fmt.Sprintf("smart_resizing = %t", dw.SmartResizing))
	}
	if dw.DefaultSplitRatio != ddw.DefaultSplitRatio {
		dwindle = append(dwindle, fmt.Sprintf("default_split_ratio = %s", luaNum(dw.DefaultSplitRatio)))
	}
	if dw.ForceSplit != ddw.ForceSplit {
		dwindle = append(dwindle, fmt.Sprintf("force_split = %d", dwindleForceSplit(dw.ForceSplit)))
	}
	if dw.UseActiveForSplits != ddw.UseActiveForSplits {
		dwindle = append(dwindle, fmt.Sprintf("use_active_for_splits = %t", dw.UseActiveForSplits))
	}

	ms, dms := o.Master, d.Master
	if ms.Mfact != dms.Mfact {
		master = append(master, fmt.Sprintf("mfact = %s", luaNum(ms.Mfact)))
	}
	if ms.NewStatus != dms.NewStatus {
		master = append(master, fmt.Sprintf("new_status = %s", luaStr(ms.NewStatus)))
	}
	if ms.NewOnTop != dms.NewOnTop {
		master = append(master, fmt.Sprintf("new_on_top = %t", ms.NewOnTop))
	}
	if ms.Orientation != dms.Orientation {
		master = append(master, fmt.Sprintf("orientation = %s", luaStr(ms.Orientation)))
	}
	if ms.SmartResizing != dms.SmartResizing {
		master = append(master, fmt.Sprintf("smart_resizing = %t", ms.SmartResizing))
	}

	in, di := o.Input, d.Input
	if o.inputSaved {
		input = append(input,
			fmt.Sprintf("kb_layout = %s", luaStr(in.KbLayout)),
			fmt.Sprintf("kb_variant = %s", luaStr(in.KbVariant)),
			fmt.Sprintf("kb_options = %s", luaStr(in.KbOptions)))
	} else {
		if in.KbLayout != di.KbLayout {
			input = append(input, fmt.Sprintf("kb_layout = %s", luaStr(in.KbLayout)))
		}
		if in.KbVariant != di.KbVariant {
			input = append(input, fmt.Sprintf("kb_variant = %s", luaStr(in.KbVariant)))
		}
		if in.KbOptions != di.KbOptions {
			input = append(input, fmt.Sprintf("kb_options = %s", luaStr(in.KbOptions)))
		}
	}
	if in.NumlockByDefault != di.NumlockByDefault {
		input = append(input, fmt.Sprintf("numlock_by_default = %t", in.NumlockByDefault))
	}
	if in.FollowMouse != di.FollowMouse {
		input = append(input, fmt.Sprintf("follow_mouse = %d", in.FollowMouse))
	}
	if in.Sensitivity != di.Sensitivity {
		input = append(input, fmt.Sprintf("sensitivity = %s", luaNum(in.Sensitivity)))
	}
	if in.AccelProfile != di.AccelProfile {
		input = append(input, fmt.Sprintf("accel_profile = %s", luaStr(in.AccelProfile)))
	}
	if in.LeftHanded != di.LeftHanded {
		input = append(input, fmt.Sprintf("left_handed = %t", in.LeftHanded))
	}
	if in.MouseNaturalScroll != di.MouseNaturalScroll {
		input = append(input, fmt.Sprintf("natural_scroll = %t", in.MouseNaturalScroll))
	}
	if in.MouseScrollFactor != di.MouseScrollFactor {
		input = append(input, fmt.Sprintf("scroll_factor = %s", luaNum(in.MouseScrollFactor)))
	}
	if in.RepeatRate != di.RepeatRate {
		input = append(input, fmt.Sprintf("repeat_rate = %d", in.RepeatRate))
	}
	if in.RepeatDelay != di.RepeatDelay {
		input = append(input, fmt.Sprintf("repeat_delay = %d", in.RepeatDelay))
	}
	var touch []string
	if in.NaturalScroll != di.NaturalScroll {
		touch = append(touch, fmt.Sprintf("natural_scroll = %t", in.NaturalScroll))
	}
	if in.TapToClick != di.TapToClick {
		touch = append(touch, fmt.Sprintf("tap_to_click = %t", in.TapToClick))
	}
	if in.TapAndDrag != di.TapAndDrag {
		touch = append(touch, fmt.Sprintf("tap_and_drag = %t", in.TapAndDrag))
	}
	if in.Clickfinger != di.Clickfinger {
		touch = append(touch, fmt.Sprintf("clickfinger_behavior = %t", in.Clickfinger))
	}
	if in.MiddleEmulation != di.MiddleEmulation {
		touch = append(touch, fmt.Sprintf("middle_button_emulation = %t", in.MiddleEmulation))
	}
	if in.TouchScrollFactor != di.TouchScrollFactor {
		touch = append(touch, fmt.Sprintf("scroll_factor = %s", luaNum(in.TouchScrollFactor)))
	}
	if in.DisableWhileTyping != di.DisableWhileTyping {
		touch = append(touch, fmt.Sprintf("disable_while_typing = %t", in.DisableWhileTyping))
	}
	if len(touch) > 0 {
		input = append(input, "touchpad = { "+strings.Join(touch, ", ")+" }")
	}

	c, dc := o.Cursor, d.Cursor
	if c.InactiveTimeout != dc.InactiveTimeout {
		cursor = append(cursor, fmt.Sprintf("inactive_timeout = %d", c.InactiveTimeout))
	}
	if c.HideOnKeyPress != dc.HideOnKeyPress {
		cursor = append(cursor, fmt.Sprintf("hide_on_key_press = %t", c.HideOnKeyPress))
	}

	if in.MiddleClickPaste != di.MiddleClickPaste {
		misc = append(misc, fmt.Sprintf("middle_click_paste = %t", in.MiddleClickPaste))
	}

	if in.SwipeInvert != di.SwipeInvert {
		gestures = append(gestures, fmt.Sprintf("workspace_swipe_invert = %t", in.SwipeInvert))
	}
	if in.SwipeCreateNew != di.SwipeCreateNew {
		gestures = append(gestures, fmt.Sprintf("workspace_swipe_create_new = %t", in.SwipeCreateNew))
	}
	if in.SwipeDistance != di.SwipeDistance {
		gestures = append(gestures, fmt.Sprintf("workspace_swipe_distance = %d", in.SwipeDistance))
	}

	var sections []string
	if len(general) > 0 {
		sections = append(sections, "  general = { "+strings.Join(general, ", ")+" }")
	}
	if len(dwindle) > 0 {
		sections = append(sections, "  dwindle = { "+strings.Join(dwindle, ", ")+" }")
	}
	if len(master) > 0 {
		sections = append(sections, "  master = { "+strings.Join(master, ", ")+" }")
	}
	if len(deco) > 0 {
		sections = append(sections, "  decoration = { "+strings.Join(deco, ", ")+" }")
	}
	if len(input) > 0 {
		sections = append(sections, "  input = { "+strings.Join(input, ", ")+" }")
	}
	if len(cursor) > 0 {
		sections = append(sections, "  cursor = { "+strings.Join(cursor, ", ")+" }")
	}
	if len(misc) > 0 {
		sections = append(sections, "  misc = { "+strings.Join(misc, ", ")+" }")
	}
	if len(gestures) > 0 {
		sections = append(sections, "  gestures = { "+strings.Join(gestures, ", ")+" }")
	}
	if !o.Appearance.Animations {
		sections = append(sections, "  animations = { enabled = false }")
	}
	if len(sections) == 0 {
		return ""
	}
	return "hl.config({\n" + strings.Join(sections, ",\n") + ",\n})\n\n"
}

// dwindleForceSplit maps the friendly force-split labels onto Hyprland's
// dwindle:force_split integer (0 cursor, 1 left/top, 2 right/bottom).
func dwindleForceSplit(s string) int {
	switch s {
	case "left/top":
		return 1
	case "right/bottom":
		return 2
	default:
		return 0
	}
}

// windowRuleField maps the pretty boolean action keys onto the hl.window_rule
// field names where they differ; a wrong name here breaks the generated file.
var windowRuleField = map[string]string{
	"nodim": "no_dim", "noanim": "no_anim", "noblur": "no_blur",
	"noshadow": "no_shadow", "nofocus": "no_focus", "stayfocused": "stay_focused",
	"keepaspectratio": "keep_aspect_ratio",
}

// genTameMaximizeOnOpen refuses the maximise request an app makes as it opens,
// for every window, so it lands as an ordinary tile inside the gaps rather than
// edge to edge. It rides Hyprland's own suppress_event, so unlike niri there is
// nothing to undo after the fact and a maximise the user asks for later still
// takes. Emitted before the user's own rules so a per-app rule can still win.
func genTameMaximizeOnOpen(o Overrides) string {
	if !o.Windows.TameMaximizeOnOpen {
		return ""
	}
	return fmt.Sprintf("hl.window_rule({ name = %s, match = { class = %s }, suppress_event = %s })\n",
		luaStr("ryoku-tame-maximize-on-open"), luaStr(".*"), luaStr("maximize"))
}

func genWindowRule(i int, r WindowRule) string {
	if r.Action == "" {
		return ""
	}
	var match []string
	if r.Class != "" {
		match = append(match, fmt.Sprintf("class = %s", luaStr(r.Class)))
	}
	if r.Title != "" {
		match = append(match, fmt.Sprintf("title = %s", luaStr(r.Title)))
	}
	if len(match) == 0 {
		return ""
	}
	var prop string
	switch r.Action {
	case "float", "tile", "pin", "fullscreen", "maximize", "center", "immediate", "pseudo",
		"opaque", "xray", "nodim", "noanim", "noblur", "noshadow", "nofocus", "stayfocused",
		"keepaspectratio", "norounding", "noborder":
		field := windowRuleField[r.Action]
		switch r.Action {
		case "norounding":
			prop = "rounding = 0"
		case "noborder":
			prop = "border_size = 0"
		default:
			if field == "" {
				field = r.Action
			}
			prop = field + " = true"
		}
	case "opacity":
		prop = fmt.Sprintf("opacity = %s", luaNum(parseFloat(r.Value, 1)))
	case "size":
		w, h := parseWxH(r.Value)
		prop = fmt.Sprintf("size = { %d, %d }", w, h)
	case "move":
		x, y := parseWxH(r.Value)
		prop = fmt.Sprintf("move = { %d, %d }", x, y)
	case "workspace":
		prop = fmt.Sprintf("workspace = %s", luaStr(r.Value))
	case "idleinhibit":
		v := r.Value
		if v != "always" && v != "focus" && v != "fullscreen" {
			v = "always"
		}
		prop = fmt.Sprintf("idle_inhibit = %s", luaStr(v))
	case "suppressevent":
		v := r.Value
		if v != "maximize" && v != "fullscreen" && v != "activate" && v != "activatefocus" {
			v = "maximize"
		}
		prop = fmt.Sprintf("suppress_event = %s", luaStr(v))
	default:
		return ""
	}
	name := fmt.Sprintf("ryoku-user-%d", i+1)
	return fmt.Sprintf("hl.window_rule({ name = %s, match = { %s }, %s })\n",
		luaStr(name), strings.Join(match, ", "), prop)
}

func genLayerRule(i int, r LayerRule) string {
	if strings.TrimSpace(r.Namespace) == "" || r.Action == "" {
		return ""
	}
	var prop string
	switch r.Action {
	case "blur":
		prop = "blur = true"
	case "noanim":
		prop = "no_anim = true"
	case "blurpopups":
		prop = "blur_popups = true"
	case "xray":
		prop = "xray = true"
	case "abovelock":
		prop = "above_lock = true"
	case "noshadow":
		// legacy action: layer surfaces lost their shadow effect; drop it rather
		// than emit a field the runtime rejects (which kills the whole file).
		return ""
	case "ignorealpha":
		prop = fmt.Sprintf("ignore_alpha = %s", luaNum(parseFloat(r.Value, 0.5)))
	case "dimaround":
		prop = "dim_around = true"
	default:
		return ""
	}
	name := fmt.Sprintf("ryoku-layer-%d", i+1)
	return fmt.Sprintf("hl.layer_rule({ name = %s, match = { namespace = %s }, %s })\n",
		luaStr(name), luaStr(r.Namespace), prop)
}

// genAppOverride renders one app's overrides as a single hl.window_rule: only
// the set fields become props. numeric -1 and toggle "inherit" mean leave alone.
func genAppOverride(i int, a AppOverride) string {
	var match []string
	if a.Class != "" {
		match = append(match, fmt.Sprintf("class = %s", luaStr(a.Class)))
	}
	if a.Title != "" {
		match = append(match, fmt.Sprintf("title = %s", luaStr(a.Title)))
	}
	if len(match) == 0 {
		return ""
	}
	var props []string
	if a.Opacity >= 0 && a.Opacity <= 1 {
		props = append(props, fmt.Sprintf("opacity = %s", luaNum(a.Opacity)))
	}
	if a.Rounding >= 0 {
		props = append(props, fmt.Sprintf("rounding = %d", a.Rounding))
	}
	if a.BorderSize >= 0 {
		props = append(props, fmt.Sprintf("border_size = %d", a.BorderSize))
	}
	if a.Blur == "off" {
		props = append(props, "no_blur = true")
	}
	if a.Shadow == "off" {
		props = append(props, "no_shadow = true")
	}
	if a.Dim == "off" {
		props = append(props, "no_dim = true")
	}
	if a.Anim == "off" {
		props = append(props, "no_anim = true")
	}
	if a.Opaque == "on" {
		props = append(props, "opaque = true")
	}
	if len(props) == 0 {
		return ""
	}
	name := fmt.Sprintf("ryoku-app-%d", i+1)
	return fmt.Sprintf("hl.window_rule({ name = %s, match = { %s }, %s })\n",
		luaStr(name), strings.Join(match, ", "), strings.Join(props, ", "))
}

// genStartHook runs the cursor setcursor + any user autostart commands at session
// start; it registers after the base autostart so its setcursor wins.
func genStartHook(o Overrides) string {
	var lines []string
	d := defaultOverrides().Cursor
	if o.Cursor.Theme != d.Theme || o.Cursor.Size != d.Size {
		lines = append(lines, fmt.Sprintf("  hl.exec_cmd(%s)",
			luaStr(fmt.Sprintf("hyprctl setcursor %s %d", o.Cursor.Theme, o.Cursor.Size))))
	}
	for _, a := range o.Autostart {
		if strings.TrimSpace(a.Command) == "" {
			continue
		}
		lines = append(lines, fmt.Sprintf("  hl.exec_cmd(%s)", luaStr(a.Command)))
	}
	if len(lines) == 0 {
		return ""
	}
	return "hl.on(\"hyprland.start\", function()\n" + strings.Join(lines, "\n") + "\nend)\n"
}

// fullConfigLua sets every appearance/input leaf explicitly (not only diffs) so
// the preview eval forces the exact state, including a value moved back to its
// default.
func fullConfigLua(o Overrides, follow bool) string {
	a, in, c := o.Appearance, o.Input, o.Cursor
	dw, ms := o.Dwindle, o.Master
	general := []string{
		fmt.Sprintf("gaps_in = %d", a.GapsIn),
		fmt.Sprintf("gaps_out = %d", a.GapsOut),
		fmt.Sprintf("border_size = %d", a.BorderSize),
		fmt.Sprintf("layout = %s", luaStr(a.Layout)),
		fmt.Sprintf("resize_on_border = %t", a.ResizeOnBorder),
		fmt.Sprintf("snap = { enabled = %t }", a.SnapEnabled),
		fmt.Sprintf("extend_border_grab_area = %d", a.ExtendBorderGrab),
		fmt.Sprintf("hover_icon_on_border = %t", a.HoverIconOnBorder),
		fmt.Sprintf("no_focus_fallback = %t", a.NoFocusFallback),
		fmt.Sprintf("resize_corner = %d", a.ResizeCorner),
		fmt.Sprintf("gaps_workspaces = %d", a.GapsWorkspaces),
	}
	if !follow {
		general = append(general,
			fmt.Sprintf("[\"col.active_border\"] = %s", luaStr(luaRGB(a.ActiveBorder))),
			fmt.Sprintf("[\"col.inactive_border\"] = %s", luaStr(luaRGB(a.InactiveBorder))))
	}
	deco := []string{
		fmt.Sprintf("rounding = %d", a.Rounding),
		fmt.Sprintf("rounding_power = %s", luaNum(a.RoundingPower)),
		fmt.Sprintf("active_opacity = %s", luaNum(a.ActiveOpacity)),
		fmt.Sprintf("inactive_opacity = %s", luaNum(a.InactiveOpacity)),
		fmt.Sprintf("fullscreen_opacity = %s", luaNum(a.FullscreenOpacity)),
		fmt.Sprintf("dim_inactive = %t", a.DimInactive),
		fmt.Sprintf("dim_strength = %s", luaNum(a.DimStrength)),
		fmt.Sprintf("dim_special = %s", luaNum(a.DimSpecial)),
		fmt.Sprintf("dim_around = %s", luaNum(a.DimAround)),
		fmt.Sprintf("dim_modal = %t", a.DimModal),
		fmt.Sprintf("border_part_of_window = %t", a.BorderPartOfWindow),
		fmt.Sprintf("blur = { enabled = %t, size = %d, passes = %d, xray = %t, vibrancy = %s, noise = %s, "+
			"contrast = %s, brightness = %s, special = %t, popups = %t, ignore_opacity = %t, new_optimizations = %t, vibrancy_darkness = %s }",
			a.BlurEnabled, a.BlurSize, a.BlurPasses, a.BlurXray, luaNum(a.BlurVibrancy), luaNum(a.BlurNoise),
			luaNum(a.BlurContrast), luaNum(a.BlurBrightness), a.BlurSpecial, a.BlurPopups, a.BlurIgnoreOpacity, a.BlurNewOptimizations, luaNum(a.BlurVibrancyDarkness)),
		fmt.Sprintf("shadow = { enabled = %t, range = %d, render_power = %d, sharp = %t, scale = %s }",
			a.ShadowEnabled, a.ShadowRange, a.ShadowPower, a.ShadowSharp, luaNum(a.ShadowScale)),
		fmt.Sprintf("glow = { enabled = %t, range = %d, color = %s }",
			a.GlowEnabled, a.GlowRange, luaStr(luaRGB(a.GlowColor))),
	}
	input := []string{
		fmt.Sprintf("kb_layout = %s", luaStr(in.KbLayout)),
		fmt.Sprintf("kb_variant = %s", luaStr(in.KbVariant)),
		fmt.Sprintf("kb_options = %s", luaStr(in.KbOptions)),
		fmt.Sprintf("numlock_by_default = %t", in.NumlockByDefault),
		fmt.Sprintf("follow_mouse = %d", in.FollowMouse),
		fmt.Sprintf("sensitivity = %s", luaNum(in.Sensitivity)),
		fmt.Sprintf("accel_profile = %s", luaStr(in.AccelProfile)),
		fmt.Sprintf("left_handed = %t", in.LeftHanded),
		fmt.Sprintf("natural_scroll = %t", in.MouseNaturalScroll),
		fmt.Sprintf("scroll_factor = %s", luaNum(in.MouseScrollFactor)),
		fmt.Sprintf("repeat_rate = %d", in.RepeatRate),
		fmt.Sprintf("repeat_delay = %d", in.RepeatDelay),
		fmt.Sprintf("touchpad = { natural_scroll = %t, tap_to_click = %t, tap_and_drag = %t, "+
			"clickfinger_behavior = %t, middle_button_emulation = %t, scroll_factor = %s, disable_while_typing = %t }",
			in.NaturalScroll, in.TapToClick, in.TapAndDrag,
			in.Clickfinger, in.MiddleEmulation, luaNum(in.TouchScrollFactor), in.DisableWhileTyping),
	}
	return "hl.config({\n" +
		"  general = { " + strings.Join(general, ", ") + " },\n" +
		"  decoration = { " + strings.Join(deco, ", ") + " },\n" +
		"  input = { " + strings.Join(input, ", ") + " },\n" +
		fmt.Sprintf("  cursor = { inactive_timeout = %d, hide_on_key_press = %t },\n", c.InactiveTimeout, c.HideOnKeyPress) +
		fmt.Sprintf("  misc = { middle_click_paste = %t },\n", in.MiddleClickPaste) +
		fmt.Sprintf("  gestures = { workspace_swipe_invert = %t, workspace_swipe_create_new = %t, workspace_swipe_distance = %d },\n",
			in.SwipeInvert, in.SwipeCreateNew, in.SwipeDistance) +
		fmt.Sprintf("  animations = { enabled = %t },\n", a.Animations) +
		fmt.Sprintf("  dwindle = { preserve_split = %t, smart_split = %t, smart_resizing = %t, default_split_ratio = %s, force_split = %d, use_active_for_splits = %t },\n",
			dw.PreserveSplit, dw.SmartSplit, dw.SmartResizing, luaNum(dw.DefaultSplitRatio), dwindleForceSplit(dw.ForceSplit), dw.UseActiveForSplits) +
		fmt.Sprintf("  master = { mfact = %s, new_status = %s, new_on_top = %t, orientation = %s, smart_resizing = %t },\n",
			luaNum(ms.Mfact), luaStr(ms.NewStatus), ms.NewOnTop, luaStr(ms.Orientation), ms.SmartResizing) +
		"})\n"
}

// genAnimItem: one hl.animation override line.
func genAnimItem(it AnimItem) string {
	if strings.TrimSpace(it.Leaf) == "" {
		return ""
	}
	parts := []string{
		fmt.Sprintf("leaf = %s", luaStr(it.Leaf)),
		fmt.Sprintf("enabled = %t", it.Enabled),
		fmt.Sprintf("speed = %s", luaNum(it.Speed)),
	}
	if it.Bezier != "" {
		parts = append(parts, fmt.Sprintf("bezier = %s", luaStr(it.Bezier)))
	}
	if it.Style != "" {
		parts = append(parts, fmt.Sprintf("style = %s", luaStr(it.Style)))
	}
	return fmt.Sprintf("hl.animation({ %s })\n", strings.Join(parts, ", "))
}

// genAnimBlock = the user's bezier curves (first, so items can reference them) +
// the per-leaf animation overrides.
func genAnimBlock(o Overrides) string {
	var b strings.Builder
	for _, c := range o.Anim.Curves {
		if strings.TrimSpace(c.Name) == "" {
			continue
		}
		fmt.Fprintf(&b, "hl.curve(%s, { type = \"bezier\", points = { { %s, %s }, { %s, %s } } })\n",
			luaStr(c.Name), luaNum(c.X0), luaNum(c.Y0), luaNum(c.X1), luaNum(c.Y1))
	}
	for _, it := range o.Anim.Items {
		if a := genAnimItem(it); a != "" {
			b.WriteString(a)
		}
	}
	return b.String()
}

// genGesture: the workspace-swipe touchpad gesture when enabled.
func genGesture(o Overrides) string {
	if !o.Input.WorkspaceSwipe {
		return ""
	}
	n := o.Input.SwipeFingers
	if n < 3 {
		n = 3
	}
	return fmt.Sprintf("hl.gesture({ fingers = %d, direction = \"horizontal\", action = \"workspace\" })\n", n)
}

// wobbleCurve = an easeOutBack overshoot so a dragged float trails and settles.
const wobbleCurve = "hl.curve(\"ryokuWobble\", { type = \"bezier\", points = { { 0.34, 1.56 }, { 0.64, 1 } } })\n"

// genMotion: the window-motion toggles the Look tab owns, kept out of the
// diff-based hl.config so wobble can define its own curve. full restates the base
// feel too so a preview eval can switch a toggle back off.
func genMotion(o Overrides, full bool) string {
	a := o.Appearance
	var b strings.Builder
	switch {
	case a.WobblyWindows:
		b.WriteString(wobbleCurve)
		b.WriteString("hl.animation({ leaf = \"windowsMove\", enabled = true, speed = 5, bezier = \"ryokuWobble\" })\n")
	case full:
		b.WriteString("hl.animation({ leaf = \"windowsMove\", enabled = true, speed = 3.2, bezier = \"ryokuSettle\" })\n")
	}
	switch a.WindowStyle {
	case "slide", "gnomed":
		fmt.Fprintf(&b, "hl.animation({ leaf = \"windowsIn\", enabled = true, speed = 3.8, bezier = \"ryokuBloom\", style = %s })\n", luaStr(a.WindowStyle))
		fmt.Fprintf(&b, "hl.animation({ leaf = \"windowsOut\", enabled = true, speed = 2.4, bezier = \"ryokuSettle\", style = %s })\n", luaStr(a.WindowStyle))
	default:
		if full {
			b.WriteString("hl.animation({ leaf = \"windowsIn\", enabled = true, speed = 3.8, bezier = \"ryokuBloom\", style = \"popin 78%\" })\n")
			b.WriteString("hl.animation({ leaf = \"windowsOut\", enabled = true, speed = 2.4, bezier = \"ryokuSettle\", style = \"popin 86%\" })\n")
		}
	}
	return b.String()
}

// gradientBorderBlock re-reads the live palette accents at load time so the
// rotating border re-themes with the wallpaper on reload.
const gradientBorderBlock = "do\n" +
	"  local ok, wc = pcall(dofile, os.getenv(\"HOME\") .. \"/.cache/ryoku/hypr-colors.lua\")\n" +
	"  local function rgb(h, f) if type(h) ~= \"string\" then h = f end return \"rgb(\" .. h:gsub(\"#\", \"\") .. \")\" end\n" +
	"  hl.config({ general = { [\"col.active_border\"] = { colors = { rgb(ok and wc and wc.active, \"#e0563b\"), rgb(ok and wc and wc.inactive, \"#313a4d\") }, angle = 45 } } })\n" +
	"end\n"

// solidBorderBlock restores the plain palette active border, for a preview that
// switches the rotating border back off.
const solidBorderBlock = "do\n" +
	"  local ok, wc = pcall(dofile, os.getenv(\"HOME\") .. \"/.cache/ryoku/hypr-colors.lua\")\n" +
	"  local function rgb(h, f) if type(h) ~= \"string\" then h = f end return \"rgb(\" .. h:gsub(\"#\", \"\") .. \")\" end\n" +
	"  hl.config({ general = { [\"col.active_border\"] = rgb(ok and wc and wc.active, \"#e0563b\") } })\n" +
	"end\n"

// borderAngleHyprSpeed maps the friendly 1..10 rotation speed onto Hyprland's
// deciseconds-per-turn (higher is slower there), clamped so a stray value can't
// stall the sweep.
func borderAngleHyprSpeed(friendly float64) float64 {
	if friendly < 1 {
		friendly = 1
	}
	if friendly > 10 {
		friendly = 10
	}
	return 110 - friendly*10
}

// genAnimatedBorder: a rotating gradient on the active window border. Off writes
// nothing to settings.lua; a preview instead stops the sweep and restores the
// solid border. The gradient reads the palette accents when colours follow the
// wallpaper, the fixed colours otherwise.
func genAnimatedBorder(o Overrides, follow, full bool) string {
	a := o.Appearance
	if !a.AnimatedBorder {
		if !full {
			return ""
		}
		var b strings.Builder
		b.WriteString("hl.animation({ leaf = \"borderangle\", enabled = false, speed = 1, bezier = \"linear\" })\n")
		if follow {
			b.WriteString(solidBorderBlock)
		}
		return b.String()
	}
	var b strings.Builder
	if follow {
		b.WriteString(gradientBorderBlock)
	} else {
		grad := fmt.Sprintf("{ colors = { %s, %s }, angle = 45 }", luaStr(luaRGB(a.ActiveBorder)), luaStr(luaRGB(a.InactiveBorder)))
		fmt.Fprintf(&b, "hl.config({ general = { [\"col.active_border\"] = %s } })\n", grad)
	}
	fmt.Fprintf(&b, "hl.animation({ leaf = \"borderangle\", enabled = true, speed = %s, bezier = \"linear\", style = \"loop\" })\n",
		luaNum(borderAngleHyprSpeed(a.BorderAngleSpeed)))
	return b.String()
}

// liveLua = the full-config preview + cursor + loaded plugins' config, applied
// flash-free via eval. Rules, keybinds, env and autostart are not previewed;
// they apply on Save via reload.
func liveLua(o Overrides) string {
	follow := borderFollowsPalette(o)
	return fullConfigLua(o, follow) + genMotion(o, true) + genAnimatedBorder(o, follow, true) +
		genAnimBlock(o) + genGesture(o) + genPluginConfig(o) +
		fmt.Sprintf("hl.exec_cmd(%s)\n", luaStr(fmt.Sprintf("hyprctl setcursor %s %d", o.Cursor.Theme, o.Cursor.Size)))
}
