package main

import (
	"fmt"
	"sort"
	"strings"

	wm "ryoku-wm"
)

// Keybind, unbind and rebind emission for the generated Hyprland config.

func genKeybind(k Keybind) string {
	if strings.TrimSpace(k.Keys) == "" {
		return ""
	}
	var dsp string
	switch k.Action {
	case "exec", "":
		if strings.TrimSpace(k.Value) == "" {
			return ""
		}
		dsp = fmt.Sprintf("hl.dsp.exec_cmd(%s)", luaStr(k.Value))
	case "close":
		dsp = "hl.dsp.window.close()"
	case "fullscreen":
		dsp = "hl.dsp.window.fullscreen()"
	case "togglefloating":
		dsp = "hl.dsp.window.float({ action = \"toggle\" })"
	default:
		return ""
	}
	bind := func(keys string) string {
		if k.Release {
			return fmt.Sprintf("hl.bind(%s, %s, { release = true })\n", luaStr(keys), dsp)
		}
		return fmt.Sprintf("hl.bind(%s, %s)\n", luaStr(keys), dsp)
	}
	out := bind(k.Keys)
	// The number pad fires whichever way NumLock sits: a custom chord on a
	// KP_<digit> binds its NumLock-off twin to the same dispatcher too, the way
	// the shipped families cover both keypad faces. Unlike a rebind, a custom
	// bind is a direct hl.bind, so it can carry the extra line here.
	for _, twin := range wm.NumpadAliases(k.Keys) {
		out += bind(twin)
	}
	return out
}

// genUnbinds drops the shipped chords a config import must release so an imported
// bind that shadows a shipped one wins. Emitted before the binds, so after
// binds.lua registered the shipped chord and before the imported bind re-adds it.
func genUnbinds(o Overrides) string {
	var b strings.Builder
	for _, c := range o.Unbinds {
		if c = strings.TrimSpace(c); c == "" {
			continue
		}
		fmt.Fprintf(&b, "hl.unbind(%s)\n", luaStr(c))
	}
	return b.String()
}

// renderRebinds is the K() lookup binds.lua consults: one [default chord] =
// chosen chord per rebind. Always a full table (return {} when empty) so
// clearing the last rebind leaves no stale entry behind.
func renderRebinds(o Overrides) []byte {
	keys := make([]string, 0, len(o.KeybindRebinds))
	for k := range o.KeybindRebinds {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString("-- Generated by Ryoku Settings (Keybinds page); change it in the GUI, not here.\nreturn {\n")
	for _, from := range keys {
		to := strings.TrimSpace(o.KeybindRebinds[from])
		from = strings.TrimSpace(from)
		if from == "" || to == "" || from == to {
			continue
		}
		// A family rebind is stored as one {n} entry, but binds.lua binds each
		// member and both number-pad faces through its own K() lookup, so expand
		// the placeholder into the concrete per-member entries those lookups ask
		// for. FamilyRebind guards the value shape so a stray entry cannot map ten
		// workspace keys onto one chord.
		if eff, ok := wm.FamilyRebind(from, o.KeybindRebinds); ok {
			for n := 1; n <= 10; n++ {
				fromN, toN := wm.ExpandChord(from, n), wm.ExpandChord(eff, n)
				fmt.Fprintf(&b, "\t[%s] = %s,\n", luaStr(fromN), luaStr(toN))
				// The keypad sends a second keysym with NumLock off; binds.lua
				// looks that face up too, so a keypad family also maps the twin.
				fa, ta := wm.NumpadAliases(fromN), wm.NumpadAliases(toN)
				if len(fa) > 0 && len(ta) > 0 {
					fmt.Fprintf(&b, "\t[%s] = %s,\n", luaStr(fa[0]), luaStr(ta[0]))
				}
			}
			continue
		}
		fmt.Fprintf(&b, "\t[%s] = %s,\n", luaStr(from), luaStr(to))
	}
	b.WriteString("}\n")
	return []byte(b.String())
}
